import { TTourist } from "../Users/Tourist";

export type TBookedHotel = {
    _id: string;  // Unique identifier for the booked hotel (automatically generated by MongoDB)
    hotel: {
        hotelId: string;      // Hotel ID (String, required)
        name: string;         // Hotel Name (String, required)
        chainCode: string;    // Hotel chain code (String, required)
        cityCode: string;     // City code where the hotel is located (String, required)
        latitude: number;     // Latitude (Number, required)
        longitude: number;    // Longitude (Number, required)
    };
    checkInDate: string;   // Check-in date (Date in ISO string format)
    checkOutDate: string;  // Check-out date (Date in ISO string format)
    guests: number;        // Number of guests (Number, required)
    price: number;         // Price of the booking (Number, required)
    createdBy: TTourist;   // ObjectId referencing 'User' (TTourist)
    status: 'Pending' | 'Completed' | 'Cancelled';  // Booking status (enum, default: 'Pending')
    isActive: boolean;     // Indicates if the booking is active (Boolean, default: true)
    createdAt: string;     // Automatically added timestamp (ISO string)
    updatedAt: string;     // Automatically added timestamp (ISO string)
};

