import {TTourist} from "../Users/Tourist";
import {TItinerary} from "../Itinerary/Itinerary";

export type TBookedItinerary = {
    _id: string; // Unique identifier for the booked itinerary (automatically generated by MongoDB)
    itinerary: TItinerary; // ObjectId referencing 'Itinerary'
    date: string; // Date field
    createdBy: TTourist; // ObjectId referencing 'User'
    status: 'Pending' | 'Completed' | 'Cancelled'; // Booking status
    isActive: boolean; // Indicates if the booking is active
    createdAt: string; // Automatically added timestamp
    updatedAt: string; // Automatically added timestamp
};
