import {THotel} from "../Hotel";
import {TTourist} from "../Users/Tourist";

export type TBookedHotel = {
    _id: string; // Unique identifier for the booked hotel (automatically generated by MongoDB)
    hotel: THotel; // ObjectId referencing 'Hotel'
    createdBy: TTourist; // ObjectId referencing 'User'
    status: 'Pending' | 'Completed' | 'Cancelled'; // Booking status
    isActive: boolean; // Indicates if the booking is active
    createdAt: string; // Automatically added timestamp
    updatedAt: string; // Automatically added timestamp
};
